# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Revan Sopher
tagline:          'A blog, it would seem.'
description:      'A blog, it would seem.'
url:              http://rsopher.com

author:
  name:           'Revan Sopher'

paginate:         1

github:           'revan'
resume:           'https://www.dropbox.com/s/yg1y2x58vgc7pk8/resume.pdf'
