# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bowen Xiao
tagline:          "That would be me."
description:      'A blog, it would seem.'
url:              'http://BowenXiao1999.github.io'

author:
  name:           'Bowen Xiao'

paginate_path:    "blog/page:num"
paginate:         5

resume:           '../pdf/Resume_Bowen.pdf'
# what the hell