# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Bowen Xiao
tagline:          "That would be me."
description:      'A blog, it would seem.'
url:              http://bowenXiaoCUHKSZ.io

author:
  name:           'Bowen Xiao'

paginate_path:    "blog/page:num"
paginate:         5

resume:           'https://drive.google.com/open?id=1AL_9VhJoZGKNv7N--_S2RSjUZ3NXT5aY'
